theme: jekyll-theme-cayman
timezone: Europe/Berlin
pages:
  - Home: 'index.md'
theme:
  name: 'jekyll-theme-cayman'
  palette:
    primary: 'red'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
repo_url: https://github.com/andikrueger/azure-naming-conventions
edit_uri: blob/master/docs/
